### ISSUE TITLE
Have you considered submitting this to homebrew-core?

### ISSUE THREAD

**Issue by ylluminarious** [tavianator/homebrew-tap#1]
Your `bfs` utility is quite useful and it seems popular enough to make it into the core package repository. I know that the homebrew docs caution against submitting your own program, but I think it'd be fine in this case. I'd also vouch for it in case any maintainers asked.

Honestly, I think your formula looks fine so you should be able to submit it with minimal (if any) changes.

**Comment by tavianator** [comment]
Hey sorry I never acknowledged this.  The reason I'm reluctant to do this is both that they recommend not submitting your own program, and because I don't actually have access to a mac and so can't easily test the formula.  E.g. right now the build [fails](https://travis-ci.org/tavianator/homebrew-tap/builds/474727524) on Travis because some of the test files seem to ignore the `chmod u+s`, even though the bfs job itself [succeeds](https://travis-ci.org/tavianator/bfs/jobs/474693531).  I guess Homebrew does some kind of sandboxing, but it's difficult to debug without being able to reproduce in person.

I'd be totally happy if someone else submitted this though, based on my formula or not.

**Comment by ylluminarious** [comment]
@tavianator Thanks for the feedback! I've actually converted to MacPorts over the past year, so I think I'll submit it there instead. [I had issues with Homebrew,](https://github.com/Homebrew/homebrew-core/pull/25376#issuecomment-376046845) in that they were too strict about letting formulas in and other things. I've found MacPorts a huge improvement. I still use Homebrew a little bit, but I've moved to MacPorts as much as possible. I'll ping you here once I submit it to MacPorts.

**Comment by tavianator** [comment]
Sounds good, thanks!  I believe MacPorts has already encountered and fixed the relevant sandboxing issue: https://trac.macports.org/ticket/54963.  I'll report it to Homebrew once I have time to cook up a minimal reproducer.

**Comment by ylluminarious** [comment]
@tavianator FYI, [here is the current PR for `bfs` to get into Macports](https://github.com/macports/macports-ports/pull/3421). I have not added the test files for the time being; they seemed like an unnecessary complication [since Macports does not require a test suite](https://guide.macports.org/chunked/reference.phases.html#reference.phases.introduction) for a given program to install.

**Comment by tavianator** [comment]
Great!  If they're picky about the used compiler, their [advice](https://trac.macports.org/wiki/UsingTheRightCompiler#nonstandard-ports) to do

    build.args-append CC=${configure.cc}

should work fine.  And I think this should be enough to get the test phase to work, if you want:

    test.cmd make check

**Comment by ylluminarious** [comment]
@tavianator Great, thanks for the tips! I had already added this code (very similar to yours) WRT the compiler:

```tcl
variant universal {
    build.args-append CFLAGS="${configure.universal_cflags}"
}
```

**Comment by ylluminarious** [comment]
@tavianator Looks like we got into Macports with https://github.com/macports/macports-ports/pull/3421, so I'll go ahead and close this now. Thanks for the suggestions and for making this program!
